apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server-deployment
  labels:
    app: hello-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
      - name: hello-server
        image: slateci/hello-world
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-server-service
spec:
  selector:
    app: hello-server
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: hello-server
spec:
  rules:
  - host: hello.uc.ssl-hep.org
    http:
      paths:
      - backend:
          serviceName: hello-server-service
          servicePort: 80
